name: covid_tracker
description: A new Flutter application.

publish_to: 'none'

version: 1.0.2+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  connectivity: ^3.0.3
  intl: ^0.17.0
  package_info: ^2.0.0
  version: ^2.0.0
  provider: ^5.0.0

  webview_flutter: ^2.0.4
  open_file: ^3.2.0
  permission_handler: ^7.0.0
  path_provider: ^2.0.1
  fl_chart: ^0.35.0

  dio: ^4.0.0
  google_fonts: ^2.0.0

  firebase_core: ^1.1.0
  firebase_analytics: ^8.0.2
  cloud_firestore: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/